"""
IDF Exporter Utility
====================
Generates modified EnergyPlus IDF files reflecting the AI-optimized HVAC setpoint
schedules derived from simulation control decisions.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

from loguru import logger

from app.config import get_config
from app.database.repository import get_metrics_dataframe, get_recent_decisions


def export_modified_idf(
    simulation_id: str,
    base_idf_path: str | Path | None = None,
    output_path: str | Path | None = None,
) -> Path:
    """
    Generate a modified IDF file with AI-optimized HVAC schedules hardcoded.

    Reads control decisions / metrics for `simulation_id` from DB, calculates
    average occupied and unoccupied setpoints, and injects updated Schedule:Compact
    objects into a copy of the base IDF file.

    Returns the path to the saved IDF file.
    """
    cfg = get_config()
    if base_idf_path is None:
        base_idf_path = cfg.resolve(cfg.simulation.idf_file)
    else:
        base_idf_path = Path(base_idf_path)

    if not base_idf_path.exists():
        logger.warning(f"Base IDF file not found at {base_idf_path}. Skipping IDF export.")
        # Fallback path creation
        output_path = output_path or cfg.resolve(f"outputs/modified_{simulation_id}.idf")
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(
            f"! Eco-Loop AI-Optimized Simulation Run\n! Simulation ID: {simulation_id}\n",
            encoding="utf-8",
        )
        return output_path

    # Read base IDF content
    idf_content = base_idf_path.read_text(encoding="utf-8")

    # Retrieve metrics/decisions from DB
    df = get_metrics_dataframe(simulation_id)
    decisions = get_recent_decisions(simulation_id, last_n=1000)

    # Defaults
    cool_occ = 24.0
    cool_unocc = 26.7
    heat_occ = 21.0
    heat_unocc = 15.6

    if not df.empty and "cooling_setpoint" in df.columns:
        # Separate into occupied vs unoccupied hours
        if "occupancy" in df.columns:
            occ_df = df[df["occupancy"] > 0]
            unocc_df = df[df["occupancy"] <= 0]
        else:
            occ_df = df
            unocc_df = df

        if not occ_df.empty:
            cool_occ = float(occ_df["cooling_setpoint"].mean())
            if "heating_setpoint" in occ_df.columns:
                heat_occ = float(occ_df["heating_setpoint"].mean())
        if not unocc_df.empty:
            cool_unocc = float(unocc_df["cooling_setpoint"].mean())
            if "heating_setpoint" in unocc_df.columns:
                heat_unocc = float(unocc_df["heating_setpoint"].mean())
    elif decisions:
        cool_vals = [d.cooling_setpoint for d in decisions if d.cooling_setpoint is not None]
        heat_vals = [d.heating_setpoint for d in decisions if d.heating_setpoint is not None]
        if cool_vals:
            cool_occ = sum(cool_vals) / len(cool_vals)
            cool_unocc = min(28.0, cool_occ + 2.5)
        if heat_vals:
            heat_occ = sum(heat_vals) / len(heat_vals)
            heat_unocc = max(15.0, heat_occ - 4.0)

    # Format values rounded to 1 decimal
    c_occ = round(cool_occ, 1)
    c_unocc = round(cool_unocc, 1)
    h_occ = round(heat_occ, 1)
    h_unocc = round(heat_unocc, 1)

    header_comment = f"""! =========================================================================
! ECO-LOOP AI-OPTIMIZED BUILDING MODEL (MODIFIED IDF)
! Generated by Autonomous AI Optimization Agent
! Simulation Run ID : {simulation_id}
! Generated At        : {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
!
! AI Optimization Summary:
!   - Occupied Cooling Setpoint   : {c_occ}°C (Baseline standard: 24.0°C)
!   - Unoccupied Cooling Setpoint : {c_unocc}°C (Baseline standard: 26.7°C)
!   - Occupied Heating Setpoint   : {h_occ}°C (Baseline standard: 21.0°C)
!   - Unoccupied Heating Setpoint : {h_unocc}°C (Baseline standard: 15.6°C)
! =========================================================================

"""

    # Build replacement CLGSETP_SCH Schedule:Compact
    new_clg_sch = f"""  Schedule:Compact,
    CLGSETP_SCH,             !- Name
    Temperature,             !- Schedule Type Limits Name
    Through: 12/31,          !- Field 1
    For: Weekdays SummerDesignDay, !- Field 2
    Until: 06:00,{c_unocc:.1f},       !- Field 3 (AI Unoccupied)
    Until: 22:00,{c_occ:.1f},       !- Field 5 (AI Occupied)
    Until: 24:00,{c_unocc:.1f},       !- Field 7 (AI Unoccupied)
    For: Saturday,           !- Field 9
    Until: 06:00,{c_unocc:.1f},       !- Field 10
    Until: 18:00,{c_occ:.1f},       !- Field 12
    Until: 24:00,{c_unocc:.1f},       !- Field 14
    For WinterDesignDay,     !- Field 16
    Until: 24:00,{c_unocc:.1f},       !- Field 17
    For: AllOtherDays,       !- Field 19
    Until: 24:00,{c_unocc:.1f};       !- Field 20"""

    # Build replacement HTGSETP_SCH Schedule:Compact
    new_htg_sch = f"""  Schedule:Compact,
    HTGSETP_SCH,             !- Name
    Temperature,             !- Schedule Type Limits Name
    Through: 12/31,          !- Field 1
    For: Weekdays,           !- Field 2
    Until: 06:00,{h_unocc:.1f},       !- Field 3 (AI Unoccupied)
    Until: 22:00,{h_occ:.1f},       !- Field 5 (AI Occupied)
    Until: 24:00,{h_unocc:.1f},       !- Field 7 (AI Unoccupied)
    For SummerDesignDay,     !- Field 9
    Until: 24:00,{h_unocc:.1f},       !- Field 10
    For: Saturday,           !- Field 12
    Until: 06:00,{h_unocc:.1f},       !- Field 13
    Until: 18:00,{h_occ:.1f},       !- Field 15
    Until: 24:00,{h_unocc:.1f},       !- Field 17
    For: WinterDesignDay,    !- Field 19
    Until: 24:00,{h_occ:.1f},       !- Field 20
    For: AllOtherDays,       !- Field 22
    Until: 24:00,{h_unocc:.1f};       !- Field 23"""

    # Replace CLGSETP_SCH block in IDF
    clg_pattern = re.compile(
        r"Schedule:Compact,\s*\n\s*CLGSETP_SCH,.*?;",
        re.DOTALL | re.IGNORECASE,
    )
    htg_pattern = re.compile(
        r"Schedule:Compact,\s*\n\s*HTGSETP_SCH,.*?;",
        re.DOTALL | re.IGNORECASE,
    )

    modified_idf = idf_content
    if clg_pattern.search(modified_idf):
        modified_idf = clg_pattern.sub(new_clg_sch, modified_idf)
    if htg_pattern.search(modified_idf):
        modified_idf = htg_pattern.sub(new_htg_sch, modified_idf)

    # Prepend header comment
    modified_idf = header_comment + modified_idf

    # Output path
    if output_path is None:
        output_path = cfg.resolve(f"outputs/modified_{simulation_id}.idf")
    else:
        output_path = Path(output_path)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(modified_idf, encoding="utf-8")

    # Also ensure a baseline IDF copy exists in outputs for clear deliverable submission
    baseline_copy_path = output_path.parent / "baseline_building.idf"
    if not baseline_copy_path.exists():
        baseline_copy_path.write_text(idf_content, encoding="utf-8")
        logger.info(f"Saved baseline IDF copy → {baseline_copy_path}")

    logger.info(f"Exported modified IDF snapshot → {output_path}")
    return output_path
