"""
Report Generator
=================
Produces reports in multiple formats:
  - Markdown (.md)
  - HTML (.html)
  - PDF (.pdf) via WeasyPrint
  - CSV (.csv) via pandas

Each report includes:
  - Executive summary (natural language from LLM if available)
  - Baseline vs optimized energy comparison
  - Comfort statistics (PMV, temperature)
  - Peak demand analysis
  - Carbon & cost savings
  - Recommendations
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Optional

import pandas as pd
from jinja2 import Environment, BaseLoader
from loguru import logger

from app.config import get_config
from app.database.repository import (
    compare_simulations,
    get_metrics_dataframe,
    get_simulation_summary,
    get_violations_dataframe,
    list_simulation_runs,
)


_REPORT_TEMPLATE_MD = """\
# Eco-Loop Building Optimization Report

**Generated:** {{ generated_at }}
**Simulation ID:** {{ sim_id }}
**Mode:** {{ mode }}

---

## Executive Summary

{{ executive_summary }}

---

## Energy Performance

| Metric | Baseline | Optimized | Savings |
|--------|----------|-----------|---------|
| Total Energy (kWh) | {{ base_energy | round(2) }} | {{ opt_energy | round(2) }} | {{ savings_kwh | round(2) }} kWh ({{ savings_pct | round(1) }}%) |
| Total Cost ($) | {{ base_cost | round(2) }} | {{ opt_cost | round(2) }} | ${{ cost_savings | round(2) }} |
| Carbon Emissions (kg CO₂) | {{ base_carbon | round(2) }} | {{ opt_carbon | round(2) }} | {{ carbon_savings | round(2) }} kg |
| Peak HVAC Power (kW) | {{ base_peak_hvac | round(2) }} | {{ opt_peak_hvac | round(2) }} | — |

### Energy Savings Breakdown
- **Electricity Savings:** {{ savings_kwh | round(2) }} kWh ({{ savings_pct | round(1) }}%)
- **Cost Savings:** ${{ cost_savings | round(2) }}
- **Carbon Reduction:** {{ carbon_savings | round(2) }} kg CO₂

---

## Thermal Comfort Statistics

| Metric | Value | Target |
|--------|-------|--------|
| Average PMV | {{ avg_pmv | round(3) }} | −0.5 to +0.5 |
| Average Indoor Temperature | {{ avg_temp | round(2) }}°C | 22–25°C |
| Min Indoor Temperature | {{ min_temp | round(2) }}°C | ≥ 22°C |
| Max Indoor Temperature | {{ max_temp | round(2) }}°C | ≤ 25°C |
| Total Comfort Violations | {{ violations }} | 0 (ideal) |
| Comfort Score | {{ comfort_score | round(1) }}% | 100% |

---

## Violation Analysis

{% if violations > 0 %}
The simulation recorded **{{ violations }}** comfort violations.

{{ violation_summary }}
{% else %}
✅ **No comfort violations recorded.** All conditions remained within specified bounds.
{% endif %}

---

## Recommendations

{% for rec in recommendations %}
{{ loop.index }}. {{ rec }}
{% endfor %}

---

## Simulation Details

- **Start Time:** {{ started_at }}
- **End Time:** {{ ended_at }}
- **Total Timesteps:** {{ total_timesteps }}
- **LLM Model:** {{ llm_model }}
- **Simulation Mode:** {{ sim_mode }}

---

*Report generated by Eco-Loop Building Agents v0.1.0*
"""

_REPORT_TEMPLATE_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Eco-Loop Report — {{ sim_id }}</title>
  <style>
    :root { --blue:#1565c0; --green:#00897b; --bg:#0f1117; --surface:#1a1d2e;
            --text:#e8eaf6; --muted:#90caf9; }
    * { box-sizing:border-box; }
    body { font-family:'Segoe UI',system-ui,sans-serif; background:var(--bg);
           color:var(--text); margin:0; padding:40px; line-height:1.6; }
    h1 { color:#64b5f6; font-size:2rem; border-bottom:2px solid var(--blue); padding-bottom:10px; }
    h2 { color:#80deea; margin-top:40px; }
    h3 { color:var(--muted); }
    table { width:100%; border-collapse:collapse; margin:20px 0; background:var(--surface);
            border-radius:8px; overflow:hidden; }
    th { background:var(--blue); padding:12px 16px; text-align:left; font-weight:600; }
    td { padding:10px 16px; border-bottom:1px solid rgba(255,255,255,0.06); }
    tr:last-child td { border-bottom:none; }
    .kpi-grid { display:flex; gap:16px; flex-wrap:wrap; margin:24px 0; }
    .kpi-card { background:var(--surface); border:1px solid rgba(255,255,255,0.1);
                border-radius:12px; padding:20px; flex:1; min-width:140px; text-align:center; }
    .kpi-value { font-size:1.8rem; font-weight:700; color:#64b5f6; }
    .kpi-green { color:#00CC96; }
    .kpi-label { font-size:0.8rem; color:var(--muted); text-transform:uppercase;
                 letter-spacing:0.05em; margin-top:4px; }
    .badge { display:inline-block; background:#00897b; color:#fff;
             padding:2px 10px; border-radius:20px; font-size:0.8rem; }
    .badge-warn { background:#e65100; }
    .section { margin:32px 0; }
    .summary-box { background:var(--surface); border-left:4px solid var(--green);
                   padding:20px; border-radius:8px; margin:16px 0; }
    .rec-list { list-style:none; padding:0; }
    .rec-list li { padding:8px 0; border-bottom:1px solid rgba(255,255,255,0.05); }
    .rec-list li::before { content:"→ "; color:var(--green); font-weight:700; }
    footer { margin-top:60px; text-align:center; color:#546e7a; font-size:0.85rem; }
  </style>
</head>
<body>
  <h1>🏢 Eco-Loop Building Optimization Report</h1>
  <p><strong>Generated:</strong> {{ generated_at }} &nbsp;|&nbsp;
     <strong>Simulation:</strong> {{ sim_id }} &nbsp;|&nbsp;
     <strong>Mode:</strong> <span class="badge">{{ mode }}</span></p>

  <div class="section">
    <h2>Executive Summary</h2>
    <div class="summary-box">{{ executive_summary | replace('\\n', '<br>') }}</div>
  </div>

  <div class="section">
    <h2>Key Performance Indicators</h2>
    <div class="kpi-grid">
      <div class="kpi-card"><div class="kpi-value kpi-green">{{ savings_pct | round(1) }}%</div>
        <div class="kpi-label">Energy Savings</div></div>
      <div class="kpi-card"><div class="kpi-value kpi-green">${{ cost_savings | round(2) }}</div>
        <div class="kpi-label">Cost Savings</div></div>
      <div class="kpi-card"><div class="kpi-value kpi-green">{{ carbon_savings | round(1) }} kg</div>
        <div class="kpi-label">CO₂ Saved</div></div>
      <div class="kpi-card"><div class="kpi-value {% if violations == 0 %}kpi-green{% endif %}">{{ violations }}</div>
        <div class="kpi-label">Comfort Violations</div></div>
      <div class="kpi-card"><div class="kpi-value">{{ avg_pmv | round(3) }}</div>
        <div class="kpi-label">Average PMV</div></div>
      <div class="kpi-card"><div class="kpi-value">{{ comfort_score | round(1) }}%</div>
        <div class="kpi-label">Comfort Score</div></div>
    </div>
  </div>

  <div class="section">
    <h2>Energy Performance</h2>
    <table>
      <tr><th>Metric</th><th>Baseline</th><th>Optimized</th><th>Savings</th></tr>
      <tr><td>Total Energy (kWh)</td><td>{{ base_energy | round(2) }}</td>
          <td>{{ opt_energy | round(2) }}</td>
          <td class="kpi-green">{{ savings_kwh | round(2) }} kWh ({{ savings_pct | round(1) }}%)</td></tr>
      <tr><td>Total Cost ($)</td><td>${{ base_cost | round(2) }}</td>
          <td>${{ opt_cost | round(2) }}</td>
          <td class="kpi-green">${{ cost_savings | round(2) }}</td></tr>
      <tr><td>Carbon Emissions (kg CO₂)</td><td>{{ base_carbon | round(2) }}</td>
          <td>{{ opt_carbon | round(2) }}</td>
          <td class="kpi-green">{{ carbon_savings | round(2) }} kg</td></tr>
      <tr><td>Peak HVAC Power (kW)</td><td>{{ base_peak_hvac | round(2) }}</td>
          <td>{{ opt_peak_hvac | round(2) }}</td><td>—</td></tr>
    </table>
  </div>

  <div class="section">
    <h2>Thermal Comfort</h2>
    <table>
      <tr><th>Metric</th><th>Value</th><th>Target</th><th>Status</th></tr>
      <tr><td>Average PMV</td><td>{{ avg_pmv | round(3) }}</td><td>−0.5 to +0.5</td>
          <td>{% if avg_pmv|abs < 0.5 %}<span class="badge">✓ OK</span>{% else %}<span class="badge badge-warn">⚠ Drift</span>{% endif %}</td></tr>
      <tr><td>Avg Indoor Temp</td><td>{{ avg_temp | round(2) }}°C</td><td>22–25°C</td>
          <td>{% if 22 <= avg_temp <= 25 %}<span class="badge">✓ OK</span>{% else %}<span class="badge badge-warn">⚠ OOB</span>{% endif %}</td></tr>
      <tr><td>Comfort Violations</td><td>{{ violations }}</td><td>0</td>
          <td>{% if violations == 0 %}<span class="badge">✓ None</span>{% else %}<span class="badge badge-warn">⚠ {{ violations }}</span>{% endif %}</td></tr>
    </table>
  </div>

  <div class="section">
    <h2>Recommendations</h2>
    <ul class="rec-list">
      {% for rec in recommendations %}<li>{{ rec }}</li>{% endfor %}
    </ul>
  </div>

  <footer>Generated by <strong>Eco-Loop Building Agents v0.1.0</strong></footer>
</body>
</html>
"""


def generate_report(
    simulation_id: str,
    fmt: str = "markdown",
    output_path: Optional[str] = None,
    baseline_id: Optional[str] = None,
) -> Path:
    """
    Generate a simulation report.

    Args:
        simulation_id: Target simulation to report on.
        fmt: Output format — 'markdown' | 'html' | 'pdf' | 'csv'
        output_path: Override output file path.
        baseline_id: Baseline simulation to compare against.

    Returns:
        Path to the generated report file.
    """
    cfg = get_config()
    cfg.ensure_output_dirs()

    # Resolve comparison baseline
    if baseline_id is None:
        all_runs = list_simulation_runs()
        baseline_run = next(
            (r for r in all_runs if r.mode == "baseline" and r.simulation_id != simulation_id),
            None,
        )
        baseline_id = baseline_run.simulation_id if baseline_run else None

    # Load data
    opt_summary = get_simulation_summary(simulation_id)
    base_summary = get_simulation_summary(baseline_id) if baseline_id else {}
    comparison = (
        compare_simulations(baseline_id, simulation_id)
        if baseline_id and simulation_id
        else {}
    )
    violations_df = get_violations_dataframe(simulation_id)
    opt_df = get_metrics_dataframe(simulation_id)

    # Build context
    context = _build_context(
        simulation_id, opt_summary, base_summary, comparison, violations_df, opt_df
    )

    # Determine output path
    if output_path is None:
        ext = {"markdown": "md", "html": "html", "pdf": "pdf", "csv": "csv"}.get(fmt, "md")
        output_path = str(cfg.resolve(cfg.output.reports_dir) / f"report_{simulation_id[:8]}.{ext}")

    out = cfg.resolve(output_path) if not Path(output_path).is_absolute() else Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    # Render
    if fmt == "csv":
        _write_csv(out, opt_df)
    elif fmt == "html":
        _write_html(out, context)
    elif fmt == "pdf":
        _write_pdf(out, context)
    else:
        _write_markdown(out, context)

    logger.info(f"Report written: {out}")
    return out


def _build_context(
    simulation_id: str,
    opt_summary: dict,
    base_summary: dict,
    comparison: dict,
    violations_df,
    opt_df,
) -> dict:
    """Build the Jinja2 template context dict."""
    savings_kwh = comparison.get("savings_kwh", 0)
    savings_pct = comparison.get("savings_pct", 0)
    violations = violations_df.shape[0] if not violations_df.empty else 0

    # Comfort score: % of timesteps within comfort bounds
    total_ts = opt_summary.get("total_timesteps", 1) or 1
    comfort_score = max(0.0, (1 - violations / total_ts) * 100)

    # Peak HVAC
    opt_peak_hvac = opt_df["hvac_power_kw"].max() if not opt_df.empty else 0
    base_peak_hvac = base_summary.get("peak_hvac_kw", 0)

    # Violation summary
    if not violations_df.empty:
        vc = violations_df["violation_type"].value_counts()
        violation_summary = "\n".join(
            f"- **{t}**: {c} occurrence(s)" for t, c in vc.items()
        )
    else:
        violation_summary = ""

    # Recommendations
    recommendations = _generate_recommendations(
        savings_pct, violations, opt_summary.get("avg_pmv", 0),
        opt_summary.get("avg_temp_c", 23), violations_df
    )

    # Executive summary (rule-based NLG)
    executive_summary = _generate_executive_summary(
        savings_pct, savings_kwh, comparison.get("cost_savings", 0),
        violations, comfort_score, opt_summary.get("avg_pmv", 0),
    )

    # Get simulation run details
    all_runs = list_simulation_runs()
    run = next((r for r in all_runs if r.simulation_id == simulation_id), None)

    return {
        "generated_at": datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        "sim_id": simulation_id,
        "mode": run.mode if run else "optimized",
        "executive_summary": executive_summary,
        "base_energy": base_summary.get("total_energy_kwh", 0),
        "opt_energy": opt_summary.get("total_energy_kwh", 0),
        "savings_kwh": savings_kwh,
        "savings_pct": savings_pct,
        "base_cost": base_summary.get("total_cost", 0),
        "opt_cost": opt_summary.get("total_cost", 0),
        "cost_savings": comparison.get("cost_savings", 0),
        "base_carbon": base_summary.get("total_carbon_kg", 0),
        "opt_carbon": opt_summary.get("total_carbon_kg", 0),
        "carbon_savings": comparison.get("carbon_savings_kg", 0),
        "base_peak_hvac": base_peak_hvac,
        "opt_peak_hvac": opt_peak_hvac,
        "avg_pmv": opt_summary.get("avg_pmv", 0),
        "avg_temp": opt_summary.get("avg_temp_c", 23),
        "min_temp": opt_summary.get("min_temp_c", 22),
        "max_temp": opt_summary.get("max_temp_c", 25),
        "violations": violations,
        "violation_summary": violation_summary,
        "comfort_score": comfort_score,
        "recommendations": recommendations,
        "started_at": run.started_at.isoformat() if run else "N/A",
        "ended_at": run.ended_at.isoformat() if run and run.ended_at else "N/A",
        "total_timesteps": opt_summary.get("total_timesteps", 0),
        "llm_model": run.llm_model if run else "N/A",
        "sim_mode": run.mode if run else "N/A",
    }


def _generate_executive_summary(
    savings_pct: float,
    savings_kwh: float,
    cost_savings: float,
    violations: int,
    comfort_score: float,
    avg_pmv: float,
) -> str:
    """Generate a natural language executive summary."""
    paragraphs = []

    # Energy paragraph
    if savings_pct > 5:
        paragraphs.append(
            f"The AI optimization agent achieved a {savings_pct:.1f}% reduction in electricity "
            f"consumption ({savings_kwh:.1f} kWh saved), resulting in ${cost_savings:.2f} in "
            f"cost savings compared to the baseline fixed-setpoint operation."
        )
    elif savings_pct > 0:
        paragraphs.append(
            f"The optimization agent delivered modest energy savings of {savings_pct:.1f}% "
            f"({savings_kwh:.1f} kWh) during this simulation period."
        )
    else:
        paragraphs.append(
            "The optimization agent prioritized comfort maintenance during this simulation "
            "period, with energy savings expected to improve over longer time horizons."
        )

    # Comfort paragraph
    if violations == 0:
        paragraphs.append(
            f"Occupant comfort was maintained throughout the entire simulation with zero "
            f"constraint violations. The average PMV of {avg_pmv:.3f} remained well within "
            f"the ±0.5 ASHRAE comfort band, and the overall comfort score was {comfort_score:.1f}%."
        )
    else:
        paragraphs.append(
            f"The simulation recorded {violations} comfort constraint violations. "
            f"The average PMV of {avg_pmv:.3f} indicates {'slightly warm' if avg_pmv > 0 else 'slightly cool'} "
            f"conditions on average. The overall comfort score was {comfort_score:.1f}%."
        )

    # Strategy paragraph
    paragraphs.append(
        "The agent employed dynamic setpoint adjustment based on real-time occupancy, PMV, "
        "and time-of-use electricity pricing. During unoccupied periods, aggressive setback "
        "strategies reduced HVAC energy consumption significantly while pre-conditioning "
        "was applied before peak occupancy hours to maintain comfort without peak-hour energy costs."
    )

    return "\n\n".join(paragraphs)


def _generate_recommendations(
    savings_pct: float,
    violations: int,
    avg_pmv: float,
    avg_temp: float,
    violations_df,
) -> list[str]:
    """Generate actionable recommendations based on simulation results."""
    recs = []

    if savings_pct < 5:
        recs.append(
            "Extend the optimization horizon to a full year (8,760 timesteps) to capture "
            "seasonal patterns and improve overall energy savings."
        )

    if violations > 10:
        recs.append(
            "Review HVAC capacity sizing — frequent comfort violations suggest the system "
            "may be undersized for peak occupancy loads."
        )

    if avg_pmv > 0.3:
        recs.append(
            "The building runs slightly warm on average. Consider lowering the default "
            "cooling setpoint by 0.5–1°C or improving solar shading."
        )
    elif avg_pmv < -0.3:
        recs.append(
            "The building runs slightly cool. Consider raising the heating setpoint by "
            "0.5–1°C to reduce both discomfort and heating energy."
        )

    if not violations_df.empty and "co2" in violations_df["violation_type"].values:
        recs.append(
            "CO₂ violations detected. Increase minimum ventilation airflow or install a "
            "demand-controlled ventilation (DCV) system."
        )

    recs.extend([
        "Integrate real-time weather forecast data to enable predictive pre-conditioning "
        "and further reduce peak demand.",
        "Enable dynamic electricity pricing integration for time-of-use optimization, "
        "shifting controllable loads to off-peak hours.",
        "Consider adding occupancy sensors for more accurate real-time occupancy detection "
        "rather than relying on schedule-based estimation.",
        "Review lighting control strategy — automated daylight-responsive dimming can "
        "reduce lighting energy by 30–50% in perimeter zones.",
    ])

    return recs


def _write_markdown(out: Path, ctx: dict) -> None:
    env = Environment(loader=BaseLoader())
    tmpl = env.from_string(_REPORT_TEMPLATE_MD)
    out.write_text(tmpl.render(**ctx), encoding="utf-8")


def _write_html(out: Path, ctx: dict) -> None:
    env = Environment(loader=BaseLoader())
    tmpl = env.from_string(_REPORT_TEMPLATE_HTML)
    out.write_text(tmpl.render(**ctx), encoding="utf-8")


def _write_pdf(out: Path, ctx: dict) -> None:
    """Generate PDF via WeasyPrint from the HTML template."""
    try:
        from weasyprint import HTML  # type: ignore
    except ImportError:
        logger.warning("WeasyPrint not installed. Generating HTML instead of PDF.")
        _write_html(out.with_suffix(".html"), ctx)
        return

    env = Environment(loader=BaseLoader())
    tmpl = env.from_string(_REPORT_TEMPLATE_HTML)
    html_content = tmpl.render(**ctx)
    HTML(string=html_content).write_pdf(str(out))


def _write_csv(out: Path, df: pd.DataFrame) -> None:
    if not df.empty:
        df.to_csv(str(out), index=False)
    else:
        out.write_text("No data available\n", encoding="utf-8")
